In [8]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate a (5, 4) array with scores between 50 and 100
scores = np.random.randint(50, 101, size=(5, 4))

print("Original Scores Array:\n", scores)

# 1. Score of the 3rd student (index 2) in the 2nd subject (index 1)
score_3_2 = scores[2, 1]
print(f"\n3rd student, 2nd subject: {score_3_2}")

# 2. All scores of the last 2 students
last_two_students = scores[-2:]
print("\nLast 2 students' scores:\n", last_two_students)

# 3. First 3 students (rows 0-2), subjects 2 and 3 (cols 1-2)
subset_scores = scores[:3, 1:3]
print("\nFirst 3 students, subjects 2 & 3:\n", subset_scores)

# 1. Column-wise mean (average per subject)
subject_means = np.round(scores.mean(axis=0), 2)
print("\nSubject-wise Means:", subject_means)

# 2. Apply a curve using broadcasting
curve_vals = np.array([5, 3, 7, 2])
curved_scores = scores + curve_vals

# Ensure no score exceeds 100
curved_scores = np.clip(curved_scores, 0, 100)
print("\nCurved Scores (Max 100):\n", curved_scores)

# 3. Row-wise max (best subject score per student)
student_best_scores = curved_scores.max(axis=1)
print("\nBest score per student:", student_best_scores)

# 1. Min-Max Normalization per row
row_mins = curved_scores.min(axis=1, keepdims=True)
row_maxs = curved_scores.max(axis=1, keepdims=True)

normalized_scores = (curved_scores - row_mins) / (row_maxs - row_mins)
print("\nNormalized Scores (0-1):\n", np.round(normalized_scores, 2))

# 2. Find student and subject index of the single highest value
# argmax returns the flat index; unravel_index converts it to 2D coordinates
max_idx = np.unravel_index(normalized_scores.argmax(), normalized_scores.shape)
print(f"\nHighest normalized value at Student Index: {max_idx[0]}, Subject Index: {max_idx[1]}")

# 3. Boolean Masking: Extract all scores > 90
scores_above_90 = curved_scores[curved_scores > 90]
print("\nScores strictly above 90 (1D array):", scores_above_90)

Original Scores Array:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]

3rd student, 2nd subject: 60

Last 2 students' scores:
 [[85 89 73 52]
 [71 51 73 93]]

First 3 students, subjects 2 & 3:
 [[78 64]
 [70 88]
 [60 60]]

Subject-wise Means: [74.6 69.6 71.6 75.6]

Curved Scores (Max 100):
 [[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]

Best score per student: [94 95 77 92 95]

Normalized Scores (0-1):
 [[0.96 0.43 0.   1.  ]
 [0.   0.33 1.   0.24]
 [1.   0.   0.29 0.86]
 [0.95 1.   0.68 0.  ]
 [0.54 0.   0.63 1.  ]]

Highest normalized value at Student Index: 0, Subject Index: 3

Scores strictly above 90 (1D array): [93 94 95 92 95]


# New Section